version: '3.1'

volumes:
  postgres_data:

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: thx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
